#FROM java:8
#MAINTAINER oracle
FROM alpine-jdk:base
MAINTAINER javaonfly
COPY files/ConfigServer.jar /opt/lib/
RUN mkdir /var/lib/config-repo
COPY config-repo /var/lib/config-repo
ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar", "/opt/lib/ConfigServer.jar"]
VOLUME /var/lib/config-repo
EXPOSE 9090